# ################################
# Spring BotWrap4j Config
# 2024-06-16 10:48:54
# ################################
spring:
  # noinspection SpellCheckingInspection
  botwrap4j:
    enabled: false
    telegram_clusters:
      - key: "key1"
        cluster_id: "C001" # uniqueue ID
        enabled: false # enable the config will be executed for sending message
        debugging: false # enable for debugging mode
        desc: "write your description"
        type: Markdown # type of message Markdown or HTML
        chat_id: -10000000 # chatID of your group or channel
        token: "bot_token_here" # bot token by BotFather
      - key: "key2"
        cluster_id: "C002"
        enabled: false # enable the config will be executed for sending message
        debugging: false # enable for debugging mode
        desc: "write your description"
        type: Markdown # type of message Markdown or HTML
        chat_id: -10000000 # chatID of your group or channel
        token: "bot_token_here" # bot token by BotFather
    slack_clusters:
      - key: "key1"
        cluster_id: "C001" # uniqueue ID
        enabled: false # enable the config will be executed for sending message
        debugging: false # enable for debugging mode
        desc: "write your description"
        channel_id: "123456789" # channelID of your channel
        token: "bot_token_here" # bot token
      - key: "key2"
        cluster_id: "C002" # uniqueue ID
        enabled: false # enable the config will be executed for sending message
        debugging: false # enable for debugging mode
        desc: "write your description"
        channel_id: "123456789" # channelID of your channel
        token: "bot_token_here" # bot token
