#file: noinspection SpellCheckingInspection
# ////////////////////////////
# Config Spring Database Connections
# ////////////////////////////
---
spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration # disable the DataSource autoconfiguration
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration # disable the Security autoconfiguration

# ################################
# Spring Redis4J Config
# 2024-06-16 10:48:54
# ################################
---
spring:
  # noinspection SpellCheckingInspection
  redis4j: # Redis4J specific configuration
    enabled: false # Toggle to enable or disable Redis4J
    debugging: false # Toggle debugging for Redis4J
    test_on_borrow: true # Test the connection on borrowing from the pool
    test_on_return: true # Test the connection on returning to the pool
    test_while_idle: true # Test the connection while idle in the pool
    block_when_exhausted: true # Block when the connection pool is exhausted
    shared_native_connection: true # Enable sharing of native connections across multiple clients
    num_tests_per_eviction_run: 3 # Number of tests to run on eviction
    duration_between_eviction_runs: 30s # Time between eviction runs
    # The maximum amount of time a Redis command (or operation) can take before it is considered to have timed out.
    # This timeout ensures that if a Redis command execution exceeds this duration,
    # the client library will abort the operation and throw a timeout exception.
    execution_command_timeout: 100ms
  redis: # Configuration for the Redis connection
    database: 0 # The database index to use (default is 0)
    host: 127.0.0.1 # The host where the Redis server is running
    port: 6379 # The port on which the Redis server is listening
    password: "****" # Optional password to authenticate with Redis (if required)
    timeout: 2000ms # The timeout value for connecting to Redis
    jedis: # Configuration for connection pooling with Jedis
      pool:
        max-active: 8 # Maximum number of connections in the Jedis pool
        max-idle: 8 # Maximum number of idle connections in the Jedis pool
        min-idle: 0 # Minimum number of idle connections in the Jedis pool
        max-wait: -1ms # Maximum wait time for a connection from the Jedis pool

# ################################
# Spring Rmq4j Configuration
# Last Updated: 2024-06-16 10:48:54
# ################################
---
spring:
  rmq4j:
    enabled: false # Global toggle for the Rmq4j module. Set to 'true' to enable the module.
    debugging: true # Enable debugging mode for detailed logs and error traces. Set to 'true' for more verbose logging.
    default_cluster: "cluster01" # The name of the default cluster that the application will connect to if not specified otherwise.
    clusters:
      cluster01: # Configuration for the first RabbitMQ cluster named "cluster01".
        enabled: true # Toggle to enable or disable this specific cluster configuration.
        host: 127.0.0.1  # Hostname or IP address of the RabbitMQ server for cluster01.
        port: 5672 # The port on which the RabbitMQ server is listening.
        username: guest # Username for authenticating with the RabbitMQ server.
        password: guest # Password for authenticating with the RabbitMQ server.
        virtual_host: "/" # Virtual host to be used within the RabbitMQ server.
        use_ssl: false # Boolean flag to indicate if SSL should be used for secure connections.
        desc: "The default cluster01"
      cluster02:
        enabled: true
        host: 127.0.0.1
        port: 5672
        username: tms_admin
        password: tms_admin
        virtual_host: "/vhost"
        use_ssl: false
        desc: "The default cluster02"
    configs: # Define specific configurations for exchanges, queues, and bindings within the clusters.
      - cluster_key: "cluster01" # Reference to the cluster this configuration applies to.
        dispatch_key: "DP001" # Unique dispatch key to identify this particular configuration.
        desc: "publish logs for changes order status" # Description of this configuration's purpose.
        enabled: true # Toggle to enable or disable this specific configuration.
        debugging: true # Enable debugging mode for detailed logs within this configuration.
        exchange: # Exchange settings for publishing messages.
          name: "guest_exchange" # Name of the exchange to use.
          kind: "fanout" # Type of exchange: can be 'fanout', 'topic', 'headers', or 'direct'.
          durable: true # If true, the exchange will survive server restarts.
          clearable: false # If true, the exchange will be deleted once no longer used.
          internal: false # If true, the exchange is for internal use only, not for publishing from the client.
          delayable: false # If true, the exchange supports delayed message delivery.
        queue: # Queue settings for consuming messages.
          name: "guest_queue" # Name of the queue to bind to the exchange.
          durable: true # If true, the queue will survive server restarts.
          exclusive: false # If true, the queue is exclusive to this connection and will be deleted once the connection closes.
          clearable: false # If true, the queue will be deleted once no longer used.
        bind: # Binding settings to link the exchange and the queue.
          routing_key: "guest" # Routing key for the binding. Used to route messages to the correct queue.

# ################################
# Spring BotWrap4j Config
# 2024-06-16 10:48:54
# ################################
---
spring:
  # noinspection SpellCheckingInspection
  botwrap4j:
    enabled: true
    telegram_clusters:
      - key: "worker_logging"
        cluster_id: "C001" # unique ID
        enabled: true # enable the config will be executed for sending message
        debugging: false # enable for debugging mode
        desc: "T.Worker 0000001"
        type: Markdown # type of message Markdown or HTML
        chat_id: -1002042977093 # chatID of your group or channel, t.me/javis_notify_forum_bot
        token: "6806983892:AAGcPZiuNktLFnyVWrRyOyYssECcVmNJSRo" # bot token by BotFather
      - key: "key2"
        cluster_id: "C002"
        enabled: false # enable the config will be executed for sending message
        debugging: false # enable for debugging mode
        desc: "T.Worker 0000002"
        type: Markdown # type of message Markdown or HTML
        chat_id: -10000000 # chatID of your group or channel
        token: "bot_token_here" # bot token by BotFather
    slack_clusters:
      - key: "key1"
        cluster_id: "C001" # unique ID
        enabled: false # enable the config will be executed for sending message
        debugging: false # enable for debugging mode
        desc: "S.Worker 0000001"
        channel_id: "123456789" # channelID of your channel
        token: "bot_token_here" # bot token
      - key: "key2"
        cluster_id: "C002" # unique ID
        enabled: false # enable the config will be executed for sending message
        debugging: false # enable for debugging mode
        desc: "S.Worker 0000002"
        channel_id: "123456789" # channelID of your channel
        token: "bot_token_here" # bot token
